
type "d:\learningSystemLog.JSON" >> "d:\Learning System\learningSystemLog.JSON" 
type "d:\learningSystemLog.JSON(1)" >> "d:\Learning System\learningSystemLog.JSON" 
type "d:\learningSystemLog.JSON(2)" >> "d:\Learning System\learningSystemLog.JSON" 
type "d:\learningSystemLog.JSON(3)" >> "d:\Learning System\learningSystemLog.JSON" 
type "d:\learningSystemLog.JSON(4)" >> "d:\Learning System\learningSystemLog.JSON" 
type "d:\learningSystemLog.JSON(5)" >> "d:\Learning System\learningSystemLog.JSON" 
type "d:\learningSystemLog.JSON(6)" >> "d:\Learning System\learningSystemLog.JSON" 
type "d:\learningSystemLog.JSON(7)" >> "d:\Learning System\learningSystemLog.JSON" 
type "d:\learningSystemLog.JSON(8)" >> "d:\Learning System\learningSystemLog.JSON" 
type "d:\learningSystemLog.JSON(9)" >> "d:\Learning System\learningSystemLog.JSON" 

del /q  "d:\learningSystemLog.JSON"  
del /q  "d:\learningSystemLog(1).JSON"  
del /q  "d:\learningSystemLog(2).JSON"  
del /q  "d:\learningSystemLog(3).JSON"  
del /q  "d:\learningSystemLog(4).JSON"  
del /q  "d:\learningSystemLog(5).JSON"  
del /q  "d:\learningSystemLog(6).JSON"  
del /q  "d:\learningSystemLog(7).JSON"  
del /q  "d:\learningSystemLog(8).JSON"  
del /q  "d:\learningSystemLog(9).JSON"  


move /Y "d:\learningSystemData.js" "d:\Learning System\learningSystemData.js" 
move /Y "d:\learningSystemData(1).js" "d:\Learning System\learningSystemData.js" 
move /Y "d:\learningSystemData(2).js" "d:\Learning System\learningSystemData.js" 
move /Y "d:\learningSystemData(3).js" "d:\Learning System\learningSystemData.js" 
move /Y "d:\learningSystemData(4).js" "d:\Learning System\learningSystemData.js" 
move /Y "d:\learningSystemData(5).js" "d:\Learning System\learningSystemData.js" 
move /Y "d:\learningSystemData(6).js" "d:\Learning System\learningSystemData.js" 
move /Y "d:\learningSystemData(7).js" "d:\Learning System\learningSystemData.js" 
move /Y "d:\learningSystemData(8).js" "d:\Learning System\learningSystemData.js" 
move /Y "d:\learningSystemData(9).js" "d:\Learning System\learningSystemData.js" 

"d:\Learning System\learningSystemMain.html"